In [1]:
import pandas as pd
import numpy as np

matches =  pd.read_csv('../data/matches.csv')
deliveries = pd.read_csv('../data/deliveries.csv')

print("Matches Shape:", matches.shape)
print("Deliveries Shape:", deliveries.shape)

Matches Shape: (1095, 20)
Deliveries Shape: (260920, 17)

In [2]:
print(matches.columns.tolist())

['id', 'season', 'city', 'date', 'match_type', 'player_of_match', 'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin', 'target_runs', 'target_overs', 'super_over', 'method', 'umpire1', 'umpire2']

In [3]:
print(deliveries.columns.tolist())

['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket', 'player_dismissed', 'dismissal_kind', 'fielder']

In [4]:
# Total score in first innings

total_score_df = deliveries.groupby(['match_id', 'inning']).sum()['total_runs'].reset_index()

total_score_df = total_score_df[total_score_df['inning'] == 1]

total_score_df['total_score'] = total_score_df['total_runs']

total_score_df.head()

   match_id  inning  total_runs  total_score
0    335982       1         222          222
2    335983       1         240          240
4    335984       1         129          129
6    335985       1         165          165
8    335986       1         110          110

In [5]:
# Merge first innings score with matches

match_df = matches.merge(
    total_score_df[['match_id', 'total_score']],
    left_on='id',
    right_on='match_id'
)

match_df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,match_id,total_score
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,335982,222
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,335983,240
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,335984,129
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,335985,165
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,335986,110

In [6]:
match_df = match_df[
    ['match_id',
     'city',
     'winner',
     'total_score']
]

match_df.head()

   match_id        city                       winner  total_score
0    335982   Bangalore        Kolkata Knight Riders          222
1    335983  Chandigarh          Chennai Super Kings          240
2    335984       Delhi             Delhi Daredevils          129
3    335985      Mumbai  Royal Challengers Bangalore          165
4    335986     Kolkata        Kolkata Knight Riders          110

In [7]:
print(deliveries['batting_team'].unique())

<StringArray>
[      'Kolkata Knight Riders', 'Royal Challengers Bangalore',
         'Chennai Super Kings',             'Kings XI Punjab',
            'Rajasthan Royals',            'Delhi Daredevils',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',     'Rising Pune Supergiants',
               'Gujarat Lions',      'Rising Pune Supergiant',
              'Delhi Capitals',                'Punjab Kings',
        'Lucknow Super Giants',              'Gujarat Titans',
 'Royal Challengers Bengaluru']
Length: 19, dtype: str

## TEAM NAME CLEANING

In [8]:
match_df['winner'] = match_df['winner'].replace('Delhi Daredevils','Delhi Capitals')
match_df['winner'] = match_df['winner'].replace('Kings XI Punjab','Punjab Kings')
match_df['winner'] = match_df['winner'].replace('Royal Challengers Bengaluru','Royal Challengers Bangalore')

deliveries['batting_team'] = deliveries['batting_team'].replace('Delhi Daredevils','Delhi Capitals')
deliveries['batting_team'] = deliveries['batting_team'].replace('Kings XI Punjab','Punjab Kings')
deliveries['batting_team'] = deliveries['batting_team'].replace('Royal Challengers Bengaluru','Royal Challengers Bangalore')

deliveries['bowling_team'] = deliveries['bowling_team'].replace('Delhi Daredevils','Delhi Capitals')
deliveries['bowling_team'] = deliveries['bowling_team'].replace('Kings XI Punjab','Punjab Kings')
deliveries['bowling_team'] = deliveries['bowling_team'].replace('Royal Challengers Bengaluru','Royal Challengers Bangalore')

In [9]:
second_innings = deliveries[deliveries['inning'] == 2]

second_innings.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
124,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,AB Dinda,W Jaffer,1,0,1,NaN,0,NaN,NaN,NaN
125,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,AB Dinda,R Dravid,0,1,1,wides,0,NaN,NaN,NaN
126,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,AB Dinda,R Dravid,0,0,0,NaN,0,NaN,NaN,NaN
127,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,AB Dinda,R Dravid,1,0,1,NaN,0,NaN,NaN,NaN
128,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,AB Dinda,W Jaffer,1,0,1,NaN,0,NaN,NaN,NaN

In [10]:
second_innings = second_innings.merge(
    match_df,
    left_on='match_id',
    right_on='match_id'
)

second_innings.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,city,winner,total_score
0,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,AB Dinda,W Jaffer,1,0,1,NaN,0,NaN,NaN,NaN,Bangalore,Kolkata Knight Riders,222
1,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,AB Dinda,R Dravid,0,1,1,wides,0,NaN,NaN,NaN,Bangalore,Kolkata Knight Riders,222
2,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,AB Dinda,R Dravid,0,0,0,NaN,0,NaN,NaN,NaN,Bangalore,Kolkata Knight Riders,222
3,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,AB Dinda,R Dravid,1,0,1,NaN,0,NaN,NaN,NaN,Bangalore,Kolkata Knight Riders,222
4,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,AB Dinda,W Jaffer,1,0,1,NaN,0,NaN,NaN,NaN,Bangalore,Kolkata Knight Riders,222

In [11]:
second_innings['current_score'] = second_innings.groupby('match_id')['total_runs'].cumsum()

second_innings[['match_id','current_score']].head()

   match_id  current_score
0    335982              1
1    335982              2
2    335982              2
3    335982              3
4    335982              4

In [12]:
second_innings['runs_left'] = second_innings['total_score'] - second_innings['current_score'] + 1

second_innings[['total_score','current_score','runs_left']].head()

   total_score  current_score  runs_left
0          222              1        222
1          222              2        221
2          222              2        221
3          222              3        220
4          222              4        219

In [15]:
second_innings['balls_left'] = 120 - (
    second_innings['over'] * 6 + second_innings['ball']
)

second_innings[['over','ball','balls_left']].head()

   over  ball  balls_left
0     0     1         119
1     0     2         118
2     0     3         117
3     0     4         116
4     0     5         115

## WICKETS LEFT

In [16]:
second_innings['player_dismissed'] = second_innings['player_dismissed'].fillna("0")

wickets = second_innings['player_dismissed'].apply(
    lambda x: 0 if x == "0" else 1
).groupby(second_innings['match_id']).cumsum()

second_innings['wickets_left'] = 10 - wickets

second_innings[['wickets_left']].head()

   wickets_left
0            10
1            10
2            10
3            10
4            10

## RUN RATE (CRR)

In [17]:
second_innings['crr'] = (
    second_innings['current_score'] * 6
) / (
    120 - second_innings['balls_left']
)

In [18]:
second_innings[['current_score','balls_left','crr']].head()

   current_score  balls_left  crr
0              1         119  6.0
1              2         118  6.0
2              2         117  4.0
3              3         116  4.5
4              4         115  4.8

## (RRR)

In [20]:
second_innings['rrr'] = (
    second_innings['runs_left'] * 6
) / second_innings['balls_left']

In [21]:
second_innings[['runs_left','balls_left','rrr']].head()

   runs_left  balls_left        rrr
0        222         119  11.193277
1        221         118  11.237288
2        221         117  11.333333
3        220         116  11.379310
4        219         115  11.426087

## Result Column (Win/Lose)

In [22]:
second_innings['result'] = np.where(
    second_innings['batting_team'] == second_innings['winner'],
    1,
    0
)

second_innings[['batting_team','winner','result']].head()

                  batting_team                 winner  result
0  Royal Challengers Bangalore  Kolkata Knight Riders       0
1  Royal Challengers Bangalore  Kolkata Knight Riders       0
2  Royal Challengers Bangalore  Kolkata Knight Riders       0
3  Royal Challengers Bangalore  Kolkata Knight Riders       0
4  Royal Challengers Bangalore  Kolkata Knight Riders       0

## Final Dataset

In [23]:
final_df = second_innings[
    [
        'batting_team',
        'bowling_team',
        'city',
        'runs_left',
        'balls_left',
        'wickets_left',
        'total_score',
        'crr',
        'rrr',
        'result'
    ]
]

final_df.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_score,crr,rrr,result
0,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,222,119,10,222,6.0,11.193277,0
1,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,221,118,10,222,6.0,11.237288,0
2,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,221,117,10,222,4.0,11.333333,0
3,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,220,116,10,222,4.5,11.379310,0
4,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,219,115,10,222,4.8,11.426087,0

## Remove Missing Values

In [24]:
final_df = final_df.dropna()

final_df.shape

(119713, 10)

## Shuffle Dataset

In [25]:
final_df = final_df.sample(final_df.shape[0])

final_df.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_score,crr,rrr,result
65630,Sunrisers Hyderabad,Gujarat Lions,Delhi,45,24,4,162,7.375000,11.250000,1
103412,Delhi Capitals,Royal Challengers Bangalore,Mumbai,56,24,5,189,8.375000,14.000000,0
57097,Rajasthan Royals,Sunrisers Hyderabad,Mumbai,158,76,8,201,6.000000,12.473684,0
9805,Rajasthan Royals,Royal Challengers Bangalore,Centurion,106,118,10,105,0.000000,5.389831,1
35442,Mumbai Indians,Kolkata Knight Riders,Mumbai,105,76,9,140,4.909091,8.289474,0

## Split X and y

In [26]:
X = final_df.drop('result', axis=1)
y = final_df['result']

print(X.shape)
print(y.shape)

(119713, 9)
(119713,)

## Train-Test Split

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [28]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer([
    ('trf', OneHotEncoder(sparse_output=False, handle_unknown='ignore'),
     ['batting_team','bowling_team','city'])
], remainder='passthrough')

## Random Forest Pipeline

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('transformer', trf),
    ('model', RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ))
])

## Training of the Model

In [32]:
print(final_df.isnull().sum())

batting_team    0
bowling_team    0
city            0
runs_left       0
balls_left      0
wickets_left    0
total_score     0
crr             0
rrr             0
result          0
dtype: int64

In [33]:
print(final_df.shape)

(119713, 10)

In [34]:
import numpy as np

print(np.isinf(final_df.select_dtypes(include=np.number)).sum())

runs_left         0
balls_left        0
wickets_left      0
total_score       0
crr               0
rrr             396
result            0
dtype: int64

In [35]:
import numpy as np

final_df.replace([np.inf, -np.inf], np.nan, inplace=True)

final_df.dropna(inplace=True)

print(final_df.shape)

(119317, 10)

In [36]:
X = final_df.drop('result', axis=1)
y = final_df['result']

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [38]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('model',
                 RandomForestClassifier(n_estimators=200, n_jobs=-1,
                                        random_state=42))])

## Accuracy Score

In [39]:
from sklearn.metrics import accuracy_score

y_pred = pipe.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9986171639289306

## Confusion Matrix

In [40]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[11266    18]
 [   15 12565]]

## Classification Report

In [41]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     11284
           1       1.00      1.00      1.00     12580

    accuracy                           1.00     23864
   macro avg       1.00      1.00      1.00     23864
weighted avg       1.00      1.00      1.00     23864

## Model

In [42]:
import pickle

pickle.dump(pipe, open('../model/model.pkl', 'wb'))

print("Model Saved Successfully!")

Model Saved Successfully!